### ISSUE TITLE
Heuristics for invalid headers

### ISSUE THREAD

**Issue by mnmkng** [apify/header-generator#11]
We found that some of the headers we collected in the raw data are not valid such as:

```
{
      accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'accept-encoding': 'gzip, deflate',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)',
      'Accept-Language': 'en-US'
    }
```

There probably is a better solution, but for now a good heuristic could be that we discard all header sets that:

1. use lower-case in HTTP/1.1
2. include the string `bot`.

**Comment by mnmkng** [comment]
cc @szmarczak

**Comment by szmarczak** [comment]
I would exclude both.

**Comment by Equidem** [comment]
@szmarczak Yeah, that's the plan :)
Let me know here if you notice some cases these two wouldn't catch.

Also, I am not sure yet, but I might also deduplicate the collected headers before giving them to the generator, since bots (the ones who are not trying to hide) probably always use the same set of headers, so if we only use unique headers, every bot will be represented just once, drastically decreasing the probability that their headers will appear on the output. I will have to check the data before I do that though, because if valid users also tend to have the same headers (which is certainly a possibility), it might decrease the quality of the results.

**Comment by Equidem** [comment]
Done. Also found a list of patterns created to detect known bots, so added these to the heuristics. All in all, approximately 1/6th of all the headers got filtered out.

**Comment by szmarczak** [comment]
Good job, thanks a lot :heart:
